#!groovy

def workerNode = "devel8"

pipeline {
  environment {
    GITHUB_USER = 'shm'
    GITHUB_TOKEN = credentials('ait_github_token')
    CONFLUENCE_USER = 'shm@dbc.dk'
    CONFLUENCE_TOKEN = credentials('ait_confluence_token')
  }
    agent {
        docker {
            label workerNode
            image "docker.dbc.dk/dbc-python3-deploy-env"
            alwaysPull true
            // We need to be root to apt-get and pip-install packages 
            args '-u 0:0'
        }
    }
    stages {
        stage("update confluence") {
            steps {
              sh """pip install git+https://github.com/DBCDK/pytools.git
                    github-projects-page 464519179 --verbose --topics ait"""
            }
        }
    }
}
