#!groovy

def workerNode = "devel8"

pipeline {
    agent {
        docker {
            label workerNode
            image "docker.dbc.dk/dbc-python3-deploy-env"
            alwaysPull true
            // We need to be root to apt-get and pip-install packages 
            args '-u 0:0'
        }
    }
    stages {
        stage("update confluence") {
            steps {
              environment {
                GITHUB_USER = "xp-machine-user"
                GITHUB_TOKEN = credentials('xp-machine-user')
                // CONFLUENCE_USER = credentials('')
                // CONFLUENCE_TOKEN = credentials('')
              }
              sh """pip install git+https://github.com/DBCDK/pytools.git
                    github-projects-page 464519179 --verbose --topics ait"""
            }
        }
    }
}
